version: '3.7'

services:
  db:
    container_name: db
    image: postgres:latest
    build:
      context: ./db
    ports:
      - "5432:5432"
    networks:
      - bank

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_DEFAULT_USER=admin
    ports:
      - "5672:5672"
    networks:
      - bank

networks:
  bank:
    driver: bridge
