version: '3.7'

services:
  db:
    container_name: db
    image: postgres:latest
    build:
      context: ./db
    ports:
      - "5432:5432"
    networks:
      - bank

networks:
  bank:
    driver: bridge
